site_name: Mi Página Personal
site_author: Mikel Martínez
site_url: https://mikel-martinez05.github.io

theme:
  name: readthedocs  # Prueba: material, mkdocs, readthedocs

nav:
  - Inicio: index.md
  - Sobre Mí: sobre-mi.md
  - Proyectos: proyectos.md
  - Contacto: contacto.md

repo_url: https://github.com/[tu-usuario]/[tu-usuario].github.io