site_name: Mikel Martínez
site_author: Mikel Martínez
site_url: https://mikel-martinez05.github.io

theme:
  name: material
  language: es

  palette:
    - scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/brightness-7
        name: Modo oscuro
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Modo claro

  font:
    text: "Poppins"
    code: "JetBrains Mono"

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
    - header.autohide

extra_css:
  - styles/custom.css




nav:
  - Inicio: index.md
  - Experiencia: experiencia.md
  - Formación: educacion.md
  - Contacto: contacto.md

repo_url: https://github.com/mikel-martinez05/mikel-martinez05.github.io
repo_name: mikel-martinez05/mikel-martinez05.github.io

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mikel-martinez05
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/tuusuario  # opcional, cámbialo si tienes
