site_name: Mikel Martínez
site_author: Mikel Martínez
site_url: https://mikel-martinez05.github.io

theme:
  name: material
  language: es
  palette:
    # Paleta de colores para el modo claro y oscuro
    # Prueba a cambiar 'teal' y 'indigo' por otros colores primarios y de acento
    # Colores primarios disponibles: red, pink, purple, indigo, blue, cyan, teal, green, orange, brown
    # Colores de acento disponibles: red, pink, purple, indigo, blue, cyan, teal, green, orange
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

nav:
  - Inicio: index.md
  - Sobre Mí: sobre-mi.md
  - Proyectos: proyectos.md
  - Contacto: contacto.md

repo_url: https://github.com/mikel-martinez05/mikel-martinez05.github.io
repo_name: mikel-martinez05/mikel-martinez05.github.io  